### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by horosgrisa** [atextor/icat#16]
Please, add support for webp

**Comment by atextor** [comment]
Hi @horosgrisa,
icat uses imlib2 for decoding images, so this is a feature that must be provided by this library, not by icat. Fortunately, imlib2 has a loader mechanism and someone already wrote a webp decoder as imlib2 loader: [imlib2-webp](https://github.com/gawen947/imlib2-webp). Please go there and install it, then icat will happily process webp files.
